site_name: Civi Banking
site_description: CiviBanking extension
repo_url: https://github.com/Project60/org.project60.banking
theme: 
  name: material

nav:
- Introduction: index.md
- User Guide: user-guide.md
- Configuration:
  - Concept: configuration/concept.md
  - Techie - How to create an importer: configuration/create-importer.md
  - Techie - Importer XML actions: configuration/importer-xml-actions.md
  - Techie - How to create a matcher: configuration/create-matcher.md
  - Techie - How to extend memberships when a payment is received: configuration/membership-extension-post-processor.md
  - Techie - How to create a postprocessor: configuration/create-postprocessor.md
- Developer Guide: developer-guide.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
