site_name: Civi Banking
site_description: CiviBanking extension
repo_url: https://github.com/Project60/org.project60.banking
theme: 
  name: material

nav:
- Introduction: index.md
- User Guide: user-guide.md
- Configuration:
  - Extension Settings: configuration/settings.md
  - Plugins:
    - Concept: configuration/plugins/concept.md
    - Importers: configuration/plugins/importer.md
    - Importer actions: configuration/plugins/importer-actions.md
    - Analysers and Matchers: configuration/plugins/analyser-matcher.md
    - Postprocessors: configuration/plugins/postprocessor.md
- Developer Guide: developer-guide.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
